### ISSUE TITLE
Tilaukset: Kaikkien tilausten taulukko

### ISSUE THREAD

**Issue by hennahei** [partio-scout/fj16_hankinta_backend#146]
OSIO: Tilaukset
ROOLI: Hankkija
- [ ] Tarvittaessa taulukko sivutetaan (alhaalla visualisoinnin malli).
- [ ] Hankkija voi suodattaa alasvetovalikolla näkyviin kaikki tai vain tietyt kustannuspaikat (ja myös ladata ne csv:hen).
- [ ] Rivin alun plussalla voi lisätä rivin kyseiseen tilaukseen (ks. #142)
- [ ] Tuote-sarakkeen tuotenimi on linkki, jota klikkaamalla aukeaa Katsele tuotetta -ikkuna (ks. #143).
- [ ] Hankkija voi muokata tilaamatonta tuotetta ja monistaa tilatunkin rivin (ks. #157)
- [ ] Kun tuote on tilattu, tilausriviä ei voi enää muokata eikä poistaa.
- [ ] Vapauta-sarake ja Vapauta muokattavaksi -painike nollaavat päällikön hyväksynnän ja palauttavat tilausrivin tilaajan muokattavaksi. 
- [ ] Kun päällikkö on antanut hankintaluvan, hankkija voi tilata tuotteen.
- [ ] Tilattu-sarakkeen +-painike ohjaa ulkoisiin tilauksiin ja aukaisee alla olevan ikkunan: ![hankkijan-nakyma_lisaa-ulkoiseen](https://cloud.githubusercontent.com/assets/19167211/19107704/31afb24e-8af6-11e6-9005-ddd5a82fd438.PNG) Lisää ulkoiseen tilaukseen -painike vie katsomaan sitä ulkoista tilausta, johon rivi on lisätty (aktivoituu kun joku ulkoinen tilaus on valittu) ja Luo uusi ulkoinen tilaus -painike avaa uuden ulkoisen tilauksen luomisen ikkunan ja sen luotuaan tarkastellaan kyseistä ulkoista tilausta, jossa ensimmäisenä näkyy lisätty rivi.
- [ ] Jos tuote on itsehankittava, hankkija ei voi tuotetta tilata (eli ei näy ulkoisissa tilauksissa eikä tule +-ikonia Tilattu-sarakkeeseen.
- [ ] Kun rivi on tilattu, tulee Tilattu-sarakkeeseen ulkoisen tilauksen tilausnumero.
- [ ] Toimitus-sarake kertoo sekä toivotus toimitusajankohdan että tuotteen saapumisen SAAPUNUT-merkinnällä.
- [ ] Tilaaja-sarakkeessa näkyy tilaajan nimi. 
- [ ] Loki-sarakkeen ikonia hoveroimalla näkee viimeisimmän muutoksen.
- [ ] Loki-sarakkeen ikonia klikkaamalla aukeaa ikkuna, josta näkee kaikki muutokset.

![hankkijan-nakyma_taulukko](https://cloud.githubusercontent.com/assets/19167211/19106758/cbc270ba-8af1-11e6-9ad2-cd5684f11d96.PNG)
