### ISSUE TITLE
Tilaukset: Hankintalupa ja muokkausmahdollisuudet

### ISSUE THREAD

**Issue by hennahei** [partio-scout/fj16_hankinta_backend#158]
OSIO: Tilaukset
ROOLI: Päällikkö

- [ ] Päällikkö näkee kaikkien tilaukset, MUTTA hankintaluvan hän voi antaa vain omien kustannuspaikkojensa hankinnoille eli vain niille riveille voi tulla checkbox Hankintalupa-sarakkeessa
- [ ] Tarvittaessa taulukko sivutetaan (alhaalla visualisoinnin malli).
- [ ] Päällikkö voi suodattaa alasvetovalikolla näkyviin vain tietyt kustannuspaikat.
- [ ] Rivin alun plussalla voi lisätä rivin kyseiseen tilaukseen (ks. #142)
- [ ] Tuote-sarakkeen tuotenimi on linkki, jota klikkaamalla aukeaa Katsele tuotetta -ikkuna (ks. #143).
- [ ] Päällikkö voi monistaa hyväksymänsä ja tilatunkin rivin, mutta silloin hankintalupa- ja tilaustiedot eivät monistu (ks. toiminnallisuus #157)
- [ ] Kun tuote on tilattu, tilausriviä ei voi enää muokata eikä poistaa.
- [ ] Loki-sarakkeen ikonia hoveroimalla näkee viimeisimmän muutoksen.
- [ ] Loki-sarakkeen ikonia klikkaamalla aukeaa ikkuna, josta näkee kaikki muutokset.

![paallikko_hyvaksynta](https://cloud.githubusercontent.com/assets/19167211/19110535/3597e90a-8b03-11e6-970b-8194a705a75c.PNG)
